# pull official base image
FROM node:18-alpine

ENV TZ=America/Santiago
RUN apk update && apk add tzdata \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo $TZ > /etc/timezone \
    && rm -rf /var/cache/apk/*

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY react-simplilatam/ .

# install app dependencies
RUN npm ci

# start app
EXPOSE 3000
CMD ["npm", "start"]
