# Generated by Django 4.2.3 on 2023-07-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre empresa')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('rut', models.CharField(max_length=15, verbose_name='RUT')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número telefónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre empleado')),
                ('rut', models.CharField(max_length=15, verbose_name='RUT')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_employees.companies')),
            ],
        ),
    ]
